SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS sinic;

SET default_tablespace = '';

CREATE TABLE sinic.deliveries (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    date_status_at timestamp without time zone NOT NULL,
    department_name character varying(255) NOT NULL,
    manager_code bigint NOT NULL,
    manager_name character varying(255) NOT NULL,
    municipality_code character varying(8) NOT NULL,
    municipality_name character varying(255) NOT NULL,
    observations character varying(255) NOT NULL,
    status character varying(100) NOT NULL,
    type character varying(100) NOT NULL,
    user_code bigint NOT NULL
);

ALTER TABLE sinic.deliveries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sinic.deliveries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE sinic.files (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    date_status_at timestamp without time zone NOT NULL,
    is_valid boolean,
    log character varying(1000),
    observations character varying(1000),
    status character varying(100) NOT NULL,
    url character varying(1000) NOT NULL,
    user_code bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    version character varying(50),
    delivery_id bigint NOT NULL
);

ALTER TABLE sinic.files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sinic.files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('sinic.deliveries_id_seq', 1, false);
SELECT pg_catalog.setval('sinic.files_id_seq', 1, false);

ALTER TABLE ONLY sinic.deliveries
    ADD CONSTRAINT deliveries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY sinic.files
    ADD CONSTRAINT files_pkey PRIMARY KEY (id);

ALTER TABLE ONLY sinic.deliveries
    ADD CONSTRAINT uk_a4lwgj1e93xxxnogch1s0ic08 UNIQUE (code);

ALTER TABLE ONLY sinic.files
    ADD CONSTRAINT fkg11rrlbwrakifvu7vsjc8b3t5 FOREIGN KEY (delivery_id) REFERENCES sinic.deliveries(id);